apiVersion: v1
kind: Pod
metadata:
  name: city
  labels:
   app: city
spec:
  containers:
    - name: city
      image: lucj/city:1.0
---
apiVersion: v1
kind: Service
metadata:
  name: city
spec:
  selector:
    app: city
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
     
