apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo_url: bW9uZ29kYjovL2s4c0V4ZXJjaWNlOms4c0V4ZXJjaWNlQGRiLnRlY2h3aGFsZS5pbzoyNzAxNy9tZXNzYWdlP3NzbD10cnVlJmF1dGhTb3VyY2U9YWRtaW4=
---
apiVersion: v1
kind: Pod
metadata:
  name: api
  labels:
    app: api
spec:
  containers:
  - name: api
    image: lucj/messages:1.0
    env:
    - name: MONGODB_URL
      valueFrom:
        secretKeyRef:
          name: mongo-secret
          key: mongo_url
  - name: api-volume
    image: lucj/messages:1.0
    env:
    volumeMounts:
    - name: mongo-secret
      mountPath: "/run/secrets"
      readOnly: true

  volumes:
  - name: mongo-secret
    secret:
      secretName: mongo-secret
      items:
      - key: mongo_url
        path: MONGODB_URL
