apiVersion: v1
kind: Pod
metadata:
  name: pod-quota-1
  namespace: poc
spec:
  containers:
    - name: pod-quota-1
      image: nginx:1.14-alpine
      resources:
        limits:
          memory: "800Mi"
          cpu: "800m"
        requests:
          memory: "600Mi"
          cpu: "400m"
