apiVersion: v1
kind: Pod
metadata:
  name: pod-quota-2
  namespace: poc
spec:
  containers:
    - name: pod-quota-2
      image: redis:alpine
      resources:
        limits:
          memory: "150Mi"
          cpu: "150m"
        requests:
          memory: "100Mi"
          cpu: "100m"
