apiVersion: v1
kind: Pod
metadata:
  name: wordpress
spec:
  containers:
  - name: wordpress
    image: wordpress:4.9-apache
    env:
    - name: WORDPRESS_DB_PASSWORD
      value: password
    - name: WORDPRESS_DB_HOST
      value: 127.0.0.1
  - name: mysql
    image: mysql:5.7 
    env: 
    - name: MYSQL_ROOT_PASSWORD
      value: password
    volumeMounts:
    - name: data
      mountPath: /var/lib/mysql
  volumes:
  - name: data
    emptyDir: {}
    
       
