# https://kubernetes.io/docs/concepts/storage/storage-classes/#aws-ebs
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: aws-ebs-gp2
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  iopsPerGB: "10"
  fsType: ext4
  encrypted: "true"